version: '3.4'

services:
  sotiyoalerts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets/:ro"