//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.1.2.0
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SotiyoAlerts.Data.Models
{
	/// <summary>
	/// Filter types
	/// </summary>
	[System.ComponentModel.Description("Filter types")]
	public partial class Filter
	{
		partial void Init();

		/// <summary>
		/// Default constructor. Protected due to required properties, but present because EF needs it.
		/// </summary>
		protected Filter()
		{
			ChannelFilters = new System.Collections.Generic.HashSet<global::SotiyoAlerts.Data.Models.ChannelFilter>();
			SubFilters = new System.Collections.Generic.HashSet<global::SotiyoAlerts.Data.Models.SubFilter>();

			Init();
		}

		/// <summary>
		/// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
		/// </summary>
		public static Filter CreateFilterUnsafe()
		{
			return new Filter();
		}

		/// <summary>
		/// Public constructor with required data
		/// </summary>
		/// <param name="name">Filter name</param>
		/// <param name="createtime">Database create time</param>
		public Filter(string name, DateTime createtime)
		{
			if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
			this.Name = name;

			this.CreateTime = createtime;

			ChannelFilters = new System.Collections.Generic.HashSet<global::SotiyoAlerts.Data.Models.ChannelFilter>();
			SubFilters = new System.Collections.Generic.HashSet<global::SotiyoAlerts.Data.Models.SubFilter>();
			Init();
		}

		/// <summary>
		/// Static create function (for use in LINQ queries, etc.)
		/// </summary>
		/// <param name="name">Filter name</param>
		/// <param name="createtime">Database create time</param>
		public static Filter Create(string name, DateTime createtime)
		{
			return new Filter(name, createtime);
		}

		/*************************************************************************
		 * Properties
		 *************************************************************************/

		/// <summary>
		/// Required
		/// Database create time
		/// </summary>
		[Required]
		[System.ComponentModel.Description("Database create time")]
		public DateTime CreateTime { get; set; }

		/// <summary>
		/// Identity, Indexed, Required
		/// Unique identifier
		/// </summary>
		[Key]
		[Required]
		[System.ComponentModel.Description("Unique identifier")]
		public long Id { get; set; }

		/// <summary>
		/// Database last modified time
		/// </summary>
		[System.ComponentModel.Description("Database last modified time")]
		public DateTime? ModifiedTime { get; set; }

		/// <summary>
		/// Required, Max length = 250
		/// Filter name
		/// </summary>
		[Required]
		[MaxLength(250)]
		[StringLength(250)]
		[System.ComponentModel.Description("Filter name")]
		public string Name { get; set; }

		/*************************************************************************
		 * Navigation properties
		 *************************************************************************/

		public virtual ICollection<global::SotiyoAlerts.Data.Models.ChannelFilter> ChannelFilters { get; private set; }

		public virtual ICollection<global::SotiyoAlerts.Data.Models.SubFilter> SubFilters { get; private set; }

	}
}

