//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.1.2.0
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SotiyoAlerts.Data.Models
{
	/// <summary>
	/// Sub filters
	/// </summary>
	[System.ComponentModel.Description("Sub filters")]
	public partial class SubFilter
	{
		partial void Init();

		/// <summary>
		/// Default constructor. Protected due to required properties, but present because EF needs it.
		/// </summary>
		protected SubFilter()
		{
			Init();
		}

		/// <summary>
		/// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
		/// </summary>
		public static SubFilter CreateSubFilterUnsafe()
		{
			return new SubFilter();
		}

		/// <summary>
		/// Public constructor with required data
		/// </summary>
		/// <param name="filterid">Parent Filter Id</param>
		/// <param name="name">Sub Filter Name</param>
		/// <param name="createtime">Database create time</param>
		/// <param name="filter"></param>
		public SubFilter(long filterid, string name, DateTime createtime, global::SotiyoAlerts.Data.Models.Filter filter)
		{
			this.FilterId = filterid;

			if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
			this.Name = name;

			this.CreateTime = createtime;

			if (filter == null) throw new ArgumentNullException(nameof(filter));
			this.Filter = filter;
			filter.SubFilters.Add(this);

			Init();
		}

		/// <summary>
		/// Static create function (for use in LINQ queries, etc.)
		/// </summary>
		/// <param name="filterid">Parent Filter Id</param>
		/// <param name="name">Sub Filter Name</param>
		/// <param name="createtime">Database create time</param>
		/// <param name="filter"></param>
		public static SubFilter Create(long filterid, string name, DateTime createtime, global::SotiyoAlerts.Data.Models.Filter filter)
		{
			return new SubFilter(filterid, name, createtime, filter);
		}

		/*************************************************************************
		 * Properties
		 *************************************************************************/

		/// <summary>
		/// Required
		/// Database create time
		/// </summary>
		[Required]
		[System.ComponentModel.Description("Database create time")]
		public DateTime CreateTime { get; set; }

		/// <summary>
		/// Required
		/// Parent Filter Id
		/// </summary>
		[Required]
		[System.ComponentModel.Description("Parent Filter Id")]
		public long FilterId { get; set; }

		/// <summary>
		/// Identity, Indexed, Required
		/// Unique identifier
		/// </summary>
		[Key]
		[Required]
		[System.ComponentModel.Description("Unique identifier")]
		public long Id { get; set; }

		/// <summary>
		/// Database last modified time
		/// </summary>
		[System.ComponentModel.Description("Database last modified time")]
		public DateTime? ModifiedTime { get; set; }

		/// <summary>
		/// Required, Max length = 250
		/// Sub Filter Name
		/// </summary>
		[Required]
		[MaxLength(250)]
		[StringLength(250)]
		[System.ComponentModel.Description("Sub Filter Name")]
		public string Name { get; set; }

		/*************************************************************************
		 * Navigation properties
		 *************************************************************************/

		/// <summary>
		/// Required
		/// </summary>
		public virtual global::SotiyoAlerts.Data.Models.Filter Filter { get; set; }

	}
}

